# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_topic', '0004_topic_course_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='course_no',
            field=models.IntegerField(blank=True, default=0, verbose_name='course number'),
        ),
    ]
