# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_topic_poll', '0002_auto_20150828_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicpoll',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topicpollchoice',
            name='poll',
        ),
        migrations.AlterUniqueTogether(
            name='topicpollvote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='topicpollvote',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='topicpollvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='TopicPoll',
        ),
        migrations.DeleteModel(
            name='TopicPollChoice',
        ),
        migrations.DeleteModel(
            name='TopicPollVote',
        ),
    ]
