# Generated by Django 2.1.7 on 2019-03-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_comment_poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentpoll',
            options={'verbose_name': 'comment poll', 'verbose_name_plural': 'comments polls'},
        ),
        migrations.AlterModelOptions(
            name='commentpollchoice',
            options={'ordering': ['number'], 'verbose_name': 'poll choice', 'verbose_name_plural': 'poll choices'},
        ),
    ]
