# Generated by Django 3.2.18 on 2023-04-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_comment_poll', '0002_auto_20190304_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpoll',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commentpollchoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commentpollvote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
