# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 08:48
from __future__ import unicode_literals

from django.db import migrations, models


def reorder(apps, schema_editor):
    Category = apps.get_model("spirit_category", "Category")
    order = 0
    for item in Category.objects.all().order_by('title','pk'):
        order += 1
        item.sort = order
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_category', '0005_category_reindex_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='sorting order'),
        ),
        migrations.RunPython(reorder, migrations.RunPython.noop)
    ]
