# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_category', '0006_auto_20170608_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title', 'pk'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
