# Generated by Django 2.1.5 on 2019-01-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_category', '0006_category_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='sorting order'),
        ),
    ]
