# Generated by Django 3.2.18 on 2023-04-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_comment_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenthistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
