# Generated by Django 2.1.3 on 2018-11-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_user', '0009_auto_20161114_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='', max_length=255, verbose_name='nickname'),
            preserve_default=False,
        ),
    ]
