# Generated by Django 2.1.3 on 2018-11-24 23:20

from django.db import migrations

# This can be ran multiple times, I got your back ;)
def populate_nickname(apps, schema_editor):
    from django.db.models import Subquery, OuterRef
    from ...core.conf import settings
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserProfile = apps.get_model("spirit_user", "UserProfile")
    first_user = UserProfile.objects.first()
    if first_user and not first_user.nickname:
        UserProfile.objects.all().update(
            nickname=Subquery(
                User.objects
                .filter(pk=OuterRef('user_id'))
                .values('username')[:1]))

def make_usernames_lower(apps, schema_editor):
    from django.db.models.functions import Lower
    from ...core.conf import settings
    User = apps.get_model(settings.AUTH_USER_MODEL)

    if settings.ST_CASE_INSENSITIVE_USERNAMES:
        User.objects.all().update(
            username=Lower('username'))


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_user', '0010_userprofile_nickname'),
    ]

    operations = [
        migrations.RunPython(populate_nickname),
        migrations.RunPython(make_usernames_lower)
    ]
