# Generated by Django 3.0.7 on 2020-09-22 04:49

from django.db import migrations, models
import spirit.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_user', '0011_auto_20181124_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, upload_to=spirit.user.models.avatar_path, verbose_name='avatar'),
        ),
    ]
