# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_user', '0011_auto_20180516_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Asia/Shanghai', max_length=32, verbose_name='time zone'),
        ),
    ]
