# Generated by Django 3.1.1 on 2020-10-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_user', '0012_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
