# Generated by Django 4.2.19 on 2025-02-15 08:24

from django.db import migrations, models
import spirit.core.storage
import spirit.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_user', '0014_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, storage=spirit.core.storage.select_storage, upload_to=spirit.user.models.avatar_path, verbose_name='avatar'),
        ),
    ]
