name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Py ${{ matrix.python }} / Django ${{ matrix.django }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.11']
        django: ['4.2']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        uv sync --all-extras
        uv pip install --upgrade Django==${{ matrix.django }}
    - name: Test build
      run: |
        uv build --sdist
    - name: Run Tests
      run: |
        uv run ./spirit/extra/bin/spirit.py startproject project
        export PYTHONWARNINGS="default"
        make test
